/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewsIndexRouteImport } from './routes/crews.index'
import { Route as CrewsIdRouteImport } from './routes/crews.$id'
import { Route as HousesIndexRouteImport } from './routes/houses.index'
import { Route as HousesIdRouteImport } from './routes/houses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsIndexRoute = CrewsIndexRouteImport.update({
  id: '/crews/',
  path: '/crews/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsIdRoute = CrewsIdRouteImport.update({
  id: '/crews/$id',
  path: '/crews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/houses/',
  path: '/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/houses/$id',
  path: '/houses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crews/$id': typeof CrewsIdRoute
  '/houses/$id': typeof HousesIdRoute
  '/crews/': typeof CrewsIndexRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crews/$id': typeof CrewsIdRoute
  '/houses/$id': typeof HousesIdRoute
  '/crews': typeof CrewsIndexRoute
  '/houses': typeof HousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crews/$id': typeof CrewsIdRoute
  '/houses/$id': typeof HousesIdRoute
  '/crews/': typeof CrewsIndexRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crews/$id' | '/houses/$id' | '/crews/' | '/houses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crews/$id' | '/houses/$id' | '/crews' | '/houses'
  id: '__root__' | '/' | '/crews/$id' | '/houses/$id' | '/crews/' | '/houses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewsIdRoute: typeof CrewsIdRoute
  HousesIdRoute: typeof HousesIdRoute
  CrewsIndexRoute: typeof CrewsIndexRoute
  HousesIndexRoute: typeof HousesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/': {
      id: '/crews/'
      path: '/crews'
      fullPath: '/crews/'
      preLoaderRoute: typeof CrewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/$id': {
      id: '/crews/$id'
      path: '/crews/$id'
      fullPath: '/crews/$id'
      preLoaderRoute: typeof CrewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$id': {
      id: '/houses/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewsIdRoute: CrewsIdRoute,
  HousesIdRoute: HousesIdRoute,
  CrewsIndexRoute: CrewsIndexRoute,
  HousesIndexRoute: HousesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
