/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as EquipmentAdminRouteImport } from './routes/equipment-admin'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as PunchRouteImport } from './routes/punch'
import { Route as TodayRouteImport } from './routes/today'
import { Route as CrewsIndexRouteImport } from './routes/crews.index'
import { Route as CrewsIdRouteImport } from './routes/crews.$id'
import { Route as HousesIndexRouteImport } from './routes/houses.index'
import { Route as HousesIdRouteImport } from './routes/houses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentAdminRoute = EquipmentAdminRouteImport.update({
  id: '/equipment-admin',
  path: '/equipment-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const PunchRoute = PunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsIndexRoute = CrewsIndexRouteImport.update({
  id: '/crews/',
  path: '/crews/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsIdRoute = CrewsIdRouteImport.update({
  id: '/crews/$id',
  path: '/crews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/houses/',
  path: '/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/houses/$id',
  path: '/houses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/equipment-admin': typeof EquipmentAdminRoute
  '/money': typeof MoneyRoute
  '/punch': typeof PunchRoute
  '/today': typeof TodayRoute
  '/crews/$id': typeof CrewsIdRoute
  '/houses/$id': typeof HousesIdRoute
  '/crews/': typeof CrewsIndexRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/equipment-admin': typeof EquipmentAdminRoute
  '/money': typeof MoneyRoute
  '/punch': typeof PunchRoute
  '/today': typeof TodayRoute
  '/crews/$id': typeof CrewsIdRoute
  '/houses/$id': typeof HousesIdRoute
  '/crews': typeof CrewsIndexRoute
  '/houses': typeof HousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/equipment-admin': typeof EquipmentAdminRoute
  '/money': typeof MoneyRoute
  '/punch': typeof PunchRoute
  '/today': typeof TodayRoute
  '/crews/$id': typeof CrewsIdRoute
  '/houses/$id': typeof HousesIdRoute
  '/crews/': typeof CrewsIndexRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipment'
    | '/equipment-admin'
    | '/money'
    | '/punch'
    | '/today'
    | '/crews/$id'
    | '/houses/$id'
    | '/crews/'
    | '/houses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipment'
    | '/equipment-admin'
    | '/money'
    | '/punch'
    | '/today'
    | '/crews/$id'
    | '/houses/$id'
    | '/crews'
    | '/houses'
  id:
    | '__root__'
    | '/'
    | '/equipment'
    | '/equipment-admin'
    | '/money'
    | '/punch'
    | '/today'
    | '/crews/$id'
    | '/houses/$id'
    | '/crews/'
    | '/houses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRoute: typeof EquipmentRoute
  EquipmentAdminRoute: typeof EquipmentAdminRoute
  MoneyRoute: typeof MoneyRoute
  PunchRoute: typeof PunchRoute
  TodayRoute: typeof TodayRoute
  CrewsIdRoute: typeof CrewsIdRoute
  HousesIdRoute: typeof HousesIdRoute
  CrewsIndexRoute: typeof CrewsIndexRoute
  HousesIndexRoute: typeof HousesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-admin': {
      id: '/equipment-admin'
      path: '/equipment-admin'
      fullPath: '/equipment-admin'
      preLoaderRoute: typeof EquipmentAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punch': {
      id: '/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof PunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/': {
      id: '/crews/'
      path: '/crews'
      fullPath: '/crews/'
      preLoaderRoute: typeof CrewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/$id': {
      id: '/crews/$id'
      path: '/crews/$id'
      fullPath: '/crews/$id'
      preLoaderRoute: typeof CrewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$id': {
      id: '/houses/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRoute: EquipmentRoute,
  EquipmentAdminRoute: EquipmentAdminRoute,
  MoneyRoute: MoneyRoute,
  PunchRoute: PunchRoute,
  TodayRoute: TodayRoute,
  CrewsIdRoute: CrewsIdRoute,
  HousesIdRoute: HousesIdRoute,
  CrewsIndexRoute: CrewsIndexRoute,
  HousesIndexRoute: HousesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
